apiVersion: v1
kind: Secret
metadata:
  name: database-creds
  labels:
    app: deis-database
    heritage: deis
  annotations:
    "helm.sh/hook": pre-install
data: {{ if eq .Values.global.database_location "on-cluster"}}
  user: {{ randAlphaNum 32 | b64enc }}
  password: {{ randAlphaNum 32 | b64enc }}{{ else if eq .Values.global.database_location "off-cluster"}}
  user: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
  name: {{ .Values.postgres.name | b64enc }}
  host: {{ .Values.postgres.host | b64enc }}
  port: {{ .Values.postgres.port | b64enc }}{{ end }}
