apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-monitor-grafana
  labels:
    heritage: deis
  annotations:
    component.deis.io/version: {{ .Values.dockerTag }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: deis-monitor-grafana
  template:
    metadata:
      labels:
        app: deis-monitor-grafana
    spec:
      containers:
      - name: deis-monitor-grafana
        image: quay.io/{{.Values.org}}/grafana:{{.Values.dockerTag}}
        imagePullPolicy: {{.Values.pullPolicy}}
{{- if or (.Values.limits_cpu) (.Values.limits_memory)}}
        resources:
          limits:
{{- if (.Values.limits_cpu) }}
            cpu: {{.Values.limits_cpu}}
{{- end}}
{{- if (.Values.limits_memory) }}
            memory: {{.Values.limits_memory}}
{{- end}}
{{- end}}
        env:
        - name: "INFLUXDB_URLS"
          value: http://$(DEIS_MONITOR_INFLUXAPI_SERVICE_HOST):$(DEIS_MONITOR_INFLUXAPI_SERVICE_PORT_TRANSPORT)
        - name: "BIND_PORT"
          value: "3500"
        - name: "DEFAULT_USER"
          value: {{.Values.user}}
        - name: "DEFAULT_USER_PASSWORD"
          value: {{.Values.password}}
        ports:
        - containerPort: 3500
          name: ui
