org: "deis"
pullPolicy: "IfNotPresent"
dockerTag: v2.3.1
# limits_cpu: "100m"
# limits_memory: "50Mi"
fluentd:
  org: "deis"
  pullPolicy: "IfNotPresent"
  dockerTag: v2.4.1
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
redis:
  org: "deis"
  pullPolicy: "IfNotPresent"
  dockerTag: v2.2.2
  # limits_cpu: "100m"
  # limits_memory: "50Mi"
