name: nsqd
home: https://github.com/deis/nsqd
version: v2.2.0
description: A kubernetes based docker image for running nsqd.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
details: |-
  Workflow is an open source PaaS that makes it easy to deploy and manage applications on your own
  servers. Workflow builds on Kubernetes to provide a lightweight, Heroku-inspired workflow.
