apiVersion: v1
kind: Secret
metadata:
  name: logger-redis-creds
  labels:
    app: deis-logger-redis
    heritage: deis
  annotations:
    "helm.sh/hook": pre-install
data:
  password: {{ if eq .Values.global.logger_redis_location "off-cluster" }}{{ .Values.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
