name: registry-proxy
home: https://github.com/deis/registry-proxy
version: v1.1.0
description: Deis Workflow Registry Proxy.
maintainers:
  - name: Deis Team
    email: engineering@deis.com
details: |-
  Workflow is an open source PaaS that makes it easy to deploy and manage applications on your own
  servers. Workflow builds on Kubernetes to provide a lightweight, Heroku-inspired workflow.
